# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fab979047b5e537d95b58071d16c073d9b0874780994e6cda5176b7cca48af8ad1fde412c5ccd46f6ec1265614e7fb79cf6cdcbcd5b266737c8e09f4a08c7ef8

test:
  secret_key_base: 6ab8f0b881e4bee1fb9a50fb3da79ebe4b23e170eb5d4de98db5d1ab5c3c8929c8051eaf4687865da1b5a34c162cf665c0865716142ce1e09c042fa1ef73b6be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
